#Persistent Volume Claim for MySQL Database Storage (vProfile Application)
# =========================================================
#  vProfile MySQL Persistent Volume Claim (Storage Layer)
# =========================================================
# Purpose:
# - Allocates persistent storage for MySQL database
# - Ensures data is retained even after pod restarts
# - Uses AWS EBS storage class (gp2)
# =========================================================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pv-claim
  labels:
    app: vprodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: gp2
