#RabbitMQ Deployment (Message Broker Pod)
# =========================================================
# 🐇 vProfile RabbitMQ Deployment (Message Broker Layer)
# =========================================================
# Purpose:
# - Provides messaging queue system for vProfile application
# - Handles asynchronous communication between services
# - Used for background processing and task handling
# =========================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprormq
  labels:
    app: vprormq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vprormq
  template:
    metadata:
      labels:
        app: vprormq
    spec:
      containers:
      - name: vprormq
        image: rabbitmq
        ports:
        - name: vpro-rmq-port
          containerPort: 5672
        env:
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: rmq-pass
        - name: RABBITMQ_DEFAULT_USER
          value: "guest"


---
#RabbitMQ Internal Service (ClusterIP for Communication)
# =========================================================
# 🌐 RabbitMQ Internal Service (ClusterIP)
# =========================================================
# Purpose:
# - Exposes RabbitMQ inside Kubernetes cluster only
# - Used by application for message queue communication
# =========================================================
apiVersion: v1
kind: Service
metadata:
  name: vprormq01
spec:
  ports:
  - port: 5672
    targetPort: vpro-rmq-port
    protocol: TCP
  selector:
    app: vprormq
  type: ClusterIP
